### ISSUE TITLE
Warnings on php 7.0.x

### ISSUE THREAD

**Issue by joostvanhoof** [DaBourz/SimpleLoginSecure#11] opened 2017-08-03 11:26 UTC
**Updated (sorry relatively new to this), php 7.0.x produces several warnings**

**1**
'Uninitialized string offset: 3' in /phpass-0.3/PasswordHash.php line 115

**2**
'strpos(): Empty needle' in phpass-0.3/PasswordHash.php line 115

**3**
'crypt(): Supplied salt is not valid for DES. Possible bug in provided salt format' in phpass-0.3/PasswordHash.php line 247

**4**
With php 7.0.20 I get the following warning: 'Methods with the same name as their class will not be constructors in a future version of PHP; PasswordHash has a deprecated constructor' because in /phpass-0.3/PasswordHash.php the class name is the same as the method name.

This is [deprecated in php 7.0.x](http://php.net/manual/en/migration70.deprecated.php) and renaming the class and the references to it in the library seems like an easy fix.

**Comment by joostvanhoof** [comment] 2017-09-03 10:51
@DaBourz just a friendly ping for visibility :-)

**Comment by PHPCaptain** [comment] 2017-10-27 00:12
I've tried to provide a simple fix for those errors. Modified code is attached with all related files.
[SimpleLoginSecure-master.zip](https://github.com/DaBourz/SimpleLoginSecure/files/1420390/SimpleLoginSecure-master.zip)

Changes included:
1. Constructor to be PHP 7 compatible. Using method __construct() instead of class name as constructor

     `function __construct($iteration_count_log2, $portable_hashes)
	{
		$this->itoa64 = './0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';

		if ($iteration_count_log2 < 4 || $iteration_count_log2 > 31)
			$iteration_count_log2 = 8;
		$this->iteration_count_log2 = $iteration_count_log2;

		$this->portable_hashes = $portable_hashes;

		$this->random_state = microtime();
		if (function_exists('getmypid'))
			$this->random_state .= getmypid();
	}`

2. Warnings on line 115 seem to be caused by the $setting variable being shorter than 4 characters. This means when calling $setting[3], returns that warning. Fixed by adding if condition as below for line 115
`$count_log2 = isset($setting[3]) ? strpos($this->itoa64, $setting[3]) : 0;`

The rest of the code is attached

**Comment by hgibs** [comment] 2018-03-12 20:43
I know that phpass version 0.5 solved most of the deprecation warnings: http://www.openwall.com/phpass/

**Comment by mckaygerhard** [comment] 2020-07-02 17:04
fixed in https://github.com/codeigniterpower/SimpleLoginSecure/commit/f1bda7b9582480901594528abbe31450bc468615

**Comment by DaBourz** [comment] 2020-11-30 15:20
Fixed with the coming commit.

**Closed by DaBourz** 2020-11-30 15:20 UTC
